from bidict import bidict

maps = bidict({
    0: 'ARC_P',
    1: 'arc_standard_p',
    2: 'beach_P',
    3: 'CHN_Stadium_P',
    4: 'cs_day_p',
    5: 'cs_p',
    6: 'EuroStadium_Night_P',
    7: 'EuroStadium_P',
    8: 'EuroStadium_Rainy_P',
    9: 'eurostadium_snownight_p',
    10: 'Farm_Night_P',
    11: 'farm_p',
    12: 'Farm_UpsideDown_P',
    13: 'Labs_DoubleGoal_V2_P',
    14: 'Labs_Octagon_02_P',
    15: 'Labs_Underpass_P',
    16: 'NeoTokyo_P',
    17: 'NeoTokyo_Standard_P',
    18: 'Park_Night_P',
    19: 'Park_P',
    20: 'Park_Rainy_P',
    21: 'stadium_day_p',
    22: 'Stadium_Foggy_P',
    23: 'Stadium_P',
    24: 'Stadium_Winter_P',
    25: 'throwbackstadium_P',
    26: 'TrainStation_Dawn_P',
    27: 'TrainStation_Night_P',
    28: 'TrainStation_P',
    29: 'Underwater_P',
    30: 'UtopiaStadium_Dusk_P',
    31: 'UtopiaStadium_P',
    32: 'UtopiaStadium_Snow_P',
    33: 'Wasteland_Night_P',
    34: 'wasteland_Night_S_P',
    35: 'Wasteland_P',
    36: 'wasteland_s_p'
})

standard_maps = {
    'arc_standard_p',
    'beach_P',
    'CHN_Stadium_P',
    'cs_day_p',
    'cs_p',
    'EuroStadium_Night_P',
    'EuroStadium_P',
    'EuroStadium_Rainy_P',
    'eurostadium_snownight_p',
    'Farm_Night_P',
    'farm_p',
    'Farm_UpsideDown_P',
    'NeoTokyo_Standard_P',
    'Park_Night_P',
    'Park_P',
    'Park_Rainy_P',
    'stadium_day_p',
    'Stadium_Foggy_P',
    'Stadium_P',
    'Stadium_Winter_P',
    'TrainStation_Dawn_P',
    'TrainStation_Night_P',
    'TrainStation_P',
    'Underwater_P',
    'UtopiaStadium_Dusk_P',
    'UtopiaStadium_P',
    'UtopiaStadium_Snow_P',
    'wasteland_Night_S_P',
    'wasteland_s_p'
}
